### PR TITLE
ShoppingCart.setShoppingCartItemList() should not modify other fields…

### PR DESCRIPTION
**Pull request by btison**
… in the cart.

Root cause: ShoppingCart.setShoppingCartItemList() is called when unmarshalling the result obtained from the Cart service, and modifies the shopping cart pricing obtained from the cart service.

### CODE REVIEW

**Comment by siamaksade** [comment]
@tqvarnst

**Comment by siamaksade** [comment]
@jamesfalkner

**Comment by jaenswart** [comment]
Guys any idea when this PR would be merged? hitting this issue

**Comment by tqvarnst** [comment]
We will discuss this today. AFAIK we cannot reproduce this issue which also makes it hard to test. I'll update this merge with more details later.

**Comment by btison** [comment]
Please note that this only happens on master, using the Decision Server based pricing service. As far as I can see, the stable-ocp-3.5 does not use the pricing service.

**Comment by btison** [comment]
With the PR applied:
coolstore_006
coolstore_005
coolstore_004

**Comment by siamaksade** [comment]
+1

**Pull request merged**
